### ISSUE TITLE
A lot of 3.3.5a opcodes gives error on WowPacketParser\Misc\WowGuid.cs:line 249

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/WowPacketParser#189]
ServerToClient: SMSG_SPELL_START (0x0131) Length: 32 ConnIdx: 0 Time: 09/03/2010 21:41:00.000 Number: 129495
System.ArgumentOutOfRangeException
Specified argument was out of the range of valid values.
   at WowPacketParser.Misc.WowGuid64.GetHighType() in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Misc\WowGuid.cs:line 249
   at WowPacketParser.Misc.WowGuid.HasEntry() in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Misc\WowGuid.cs:line 15
   at WowPacketParser.Misc.Filters.CheckFilter(WowGuid guid) in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Misc\Filters.cs:line 68
   at WowPacketParser.Misc.Packet.ReadPackedGuid() in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Misc\PacketReads.cs:line 27
   at WowPacketParser.Misc.Packet.ReadPackedGuid(String name, Object[] indexes) in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Misc\PacketReads.cs:line 349
   at WowPacketParser.Parsing.Parsers.SpellHandler.HandleSpellStart(Packet packet) in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Parsing\Parsers\SpellHandler.cs:line 730
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Parsing\Handler.cs:line 146

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/WowPacketParser/commit/6576527653650940f097f496b138657df7f51c44 fixes some issues, guid 0xfffffffffffffffe still throws the exception

**Comment by Aokromes** [comment]
Now it's:


[8] Charges: 0
System.ArgumentOutOfRangeException
Specified argument was out of the range of valid values.
Parameter name: 0x00000F0F
   at WowPacketParser.Misc.WowGuid64.GetHighType() in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Misc\WowGuid.cs:line 258
   at WowPacketParser.Misc.WowGuid.HasEntry() in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Misc\WowGuid.cs:line 15
   at WowPacketParser.Misc.Filters.CheckFilter(WowGuid guid) in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Misc\Filters.cs:line 68
   at WowPacketParser.Misc.Packet.ReadPackedGuid() in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Misc\PacketReads.cs:line 27
   at WowPacketParser.Misc.Packet.ReadPackedGuid(String name, Object[] indexes) in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Misc\PacketReads.cs:line 353
   at WowPacketParser.Parsing.Parsers.SpellHandler.ReadAuraUpdateBlock(Packet packet, Int32 i) in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Parsing\Parsers\SpellHandler.cs:line 266
   at WowPacketParser.Parsing.Parsers.SpellHandler.HandleAuraUpdate(Packet packet) in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Parsing\Parsers\SpellHandler.cs:line 357
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in c:\Users\Aokromes\Desktop\src\WowPacketParser\WowPacketParser\Parsing\Handler.cs:line 146
