### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by jcmillions** [TrinityCore/WowPacketParser#256]
Loading module WowPacketParserModule.V6_0_2_19033.dll (fallback)
Loading module WowPacketParserModule.V7_0_3_22248.dll
[1/1 wowsniff_22423_2016-08-12_16-14-28.pkt]: Parsing 11.1MB of packets. Detected version V7_0_3_22423
[1/1 wowsniff_22423_2016-08-12_16-14-28.pkt]: Saved file to 'C:\Users\JC\Desktop\New folder (2)\wowsniff_22423_2016-08-12_16-14-28_parsed.txt'
[1/1 wowsniff_22423_2016-08-12_16-14-28.pkt]: Parsed 64250 (99.815%) packets successfully, 26 (0.040%) with errors, skipped 89 (0.138%) and without structure 4 (0.006%)  (total: 64369) in 00:00:28.759
1/34 - Write Hotfixes
[1/1 wowsniff_22423_2016-08-12_16-14-28.pkt] System.ArgumentException
[1/1 wowsniff_22423_2016-08-12_16-14-28.pkt] Requested value '    ' was not found.
[1/1 wowsniff_22423_2016-08-12_16-14-28.pkt]    at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at WowPacketParser.Loading.BinaryPacketReader.GetLocale() in C:\Users\JC\Desktop\WowPacketParser-master\WowPacketParser\Loading\BinaryPacketReader.cs:line 139
   at WowPacketParser.SQL.Builders.HotfixBuilder.Hotfixes() in C:\Users\JC\Desktop\WowPacketParser-master\WowPacketParser\SQL\Builders\HotfixBuilder.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at WowPacketParser.SQL.Builder.DumpSQL(String prefix, String fileName, String header) in C:\Users\JC\Desktop\WowPacketParser-master\WowPacketParser\SQL\Builder.cs:line 86
   at WowPacketParser.Loading.SniffFile.WriteSQLs() in C:\Users\JC\Desktop\WowPacketParser-master\WowPacketParser\Loading\SniffFile.cs:line 504
   at WowPacketParser.Loading.SniffFile.ProcessFileImpl() in C:\Users\JC\Desktop\WowPacketParser-master\WowPacketParser\Loading\SniffFile.cs:line 272
   at WowPacketParser.Loading.SniffFile.ProcessFile() in C:\Users\JC\Desktop\WowPacketParser-master\WowPacketParser\Loading\SniffFile.cs:line 85

QuestFlags2 has undefined flags: Unk400000

**Comment by jcmillions** [comment]
This was resolved so a mod can close this if he or she wants to.
