### ISSUE TITLE
Parsing Issue - Build 22267 22277

### ISSUE THREAD

**Issue by YamiCodenamed** [TrinityCore/WowPacketParser#558]
Unable to parse several sniffs of build 22267 and 22277, they are in the attachment
[Netherwing.zip](https://github.com/TrinityCore/WowPacketParser/files/5146151/Netherwing.zip)

**Comment by YamiCodenamed** [comment]
Incorrectly parsing, SMSG_QUERY_NPC_TEXT_RESPONSE

ServerToClient: SMSG_QUERY_NPC_TEXT_RESPONSE (0x26FB) Length: 73 ConnIdx: 0 Time: 07/21/2016 00:36:03.750 Number: 28101
Entry: 10605
[0] Probability: 0
[0] Text0: 
[0] Text1: 
[0] Language: 4161536 (4161536)
[0] [0] EmoteDelay: 0
[0] [0] EmoteID: 0 (OneShotNone)
[0] [1] EmoteDelay: 0
[0] [1] EmoteID: 0 (OneShotNone)
[0] [2] EmoteDelay: 0
[0] [2] EmoteID: 0 (OneShotNone)
[1] Probability: 9223372036854775808
[1] Text0: M
[1] Text1: 
[1] Language: 0 (Universal)
[1] [0] EmoteDelay: 0
[1] [0] EmoteID: 0 (OneShotNone)
[1] [1] EmoteDelay: 0
[1] [1] EmoteID: 0 (OneShotNone)
[1] [2] EmoteDelay: 0
[1] [2] EmoteID: 0 (OneShotNone)
System.IO.EndOfStreamException
Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadSingle()
   at WowPacketParser.Misc.Packet.ReadSingle(String name, Object[] indexes) in WowPacketParser-master\WowPacketParser\Misc\PacketReads.cs:line 361
   at WowPacketParser.Parsing.Parsers.QueryHandler.HandleNpcTextUpdate(Packet packet) in WowPacketParser-master\WowPacketParser\Parsing\Parsers\QueryHandler.cs:line 255
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in WowPacketParser-master\WowPacketParser\Parsing\Handler.cs:line 149

**Comment by funjoker** [comment]
open new issue please :D

**Comment by funjoker** [comment]
PS: what is the console ouput ?

**Comment by YamiCodenamed** [comment]
Yea looks like it really hates these particular sniffs

[1/1 test.pkt]: Parsing 10.1MB of packets. Detected version V7_0_3_22267
Processing... 100% complete
[1/1 test.pkt]: Saved file to 'test_parsed.txt'
[1/1 test.pkt]: Parsed 2537 (4.065%) packets successfully, 42179 (67.590%) with errors, skipped 87 (0.139%) and without structure 17601 (28.205%)  (total: 62404) in 00:00:07.244

**Comment by YamiCodenamed** [comment]
[ConsoleOut.txt](https://github.com/TrinityCore/WowPacketParser/files/5344610/ConsoleOut.txt)
[test_errors.txt](https://github.com/TrinityCore/WowPacketParser/files/5344611/test_errors.txt)

**Comment by funjoker** [comment]
your compile is broken.
It's not loading the fallback handlers
