### ISSUE TITLE
Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#580]
TrinityCore - WowPacketParser
File name: 9.0.2.36839_2020-12-19_17-39-35.pkt
Detected build: V9_0_2_36839
Detected locale: enUS
Targeted database: Shadowlands
Parsing date: 01/03/2021 19:47:23

```
Loading module WowPacketParserModule.V8_0_1_27101.dll (fallback)
Loading module WowPacketParserModule.V7_0_3_22248.dll (fallback)
Loading module WowPacketParserModule.V6_0_2_19033.dll (fallback)
Loading module WowPacketParserModule.V9_0_1_36216.dll
[1/1 9.0.2.36839_2020-12-19_17-39-35.pkt]: Parsing 31.6MB of packets. Detected version V9_0_2_36839
System.Collections.ListDictionaryInternal
System.OutOfMemoryException
Array dimensions exceeded supported range.
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at WowPacketParser.Loading.BinaryPacketReader.Read(Int32 number, String fileName) in D:\WowPacketParser\WowPacketParser\Loading\BinaryPacketReader.cs:line 145
   at WowPacketParser.Loading.Reader.TryRead(Packet& packet) in D:\WowPacketParser\WowPacketParser\Loading\Reader.cs:line 81
[1/1 9.0.2.36839_2020-12-19_17-39-35.pkt]: Saved file to 'D:\Release\data\9.0.2.36839_2020-12-19_17-39-35_parsed.txt'
[1/1 9.0.2.36839_2020-12-19_17-39-35.pkt]: Parsed 64423 (99.904%) packets successfully, 5 (0.008%) with errors, skipped 3 (0.005%) and without structure 54 (0.084%)  (total: 64485) in 00:00:32.351
1/72 - Write AreaTriggerTemplateData
2/72 - Write AreaTriggerTemplateVerticesData
3/72 - Write SpellAreaTriggersData
4/72 - Write ConversationActorsData
5/72 - Write ConversationActorTemplatesData
6/72 - Write ConversationLineTemplatesData
7/72 - Write ConversationTemplateData
8/72 - Write GameObjectTemplateAddon
9/72 - Write Hotfixes
10/72 - Write HotfixData
11/72 - Write HotfixBlob
12/72 - Write BroadcastText
13/72 - Write BroadcastTextLocales
14/72 - Write HotfixOptionalData
15/72 - Write LocalesCreature
16/72 - Write LocalesQuest
17/72 - Write LocalesQuestOfferReward
18/72 - Write LocalesQuestObjectives
19/72 - Write LocalesQuestGreeting
20/72 - Write LocalesQuestRequestItems
21/72 - Write LocalesPageText
22/72 - Write PlayerChoiceLocale
23/72 - Write PlayerChoiceResponseLocale
24/72 - Write StartInformation
25/72 - Write ObjectNames
26/72 - Write SniffData
27/72 - Write WeatherUpdates
28/72 - Write SceneTemplates
29/72 - Write QuestOfferReward
30/72 - Write QuestPOI
31/72 - Write QuestGreeting
32/72 - Write QuestDetails
33/72 - Write QuestRequestItems
34/72 - Write Creature
35/72 - Write GameObject
36/72 - Write SpellTargetPosition
37/72 - Write CreatureTemplateAddon
38/72 - Write CreatureTemplateScalingData
39/72 - Write ModelData
40/72 - Write NpcTrainer
41/72 - Write Trainer
42/72 - Write TrainerSpell
43/72 - Write CreatureTrainer
44/72 - Write NpcVendor
45/72 - Write CreatureEquip
46/72 - Write PointsOfInterest
47/72 - Write Gossip
48/72 - Write CreatureTemplateNonWDB
49/72 - Write CreatureText
50/72 - Write VehicleAccessory
51/72 - Write NpcSpellClick
52/72 - Write NpcSpellClickMop
53/72 - Write QuestTemplate
54/72 - Write QuestObjective
55/72 - Write QuestVisualEffect
56/72 - Write QuestRewardDisplaySpell
57/72 - Write CreatureTemplate
58/72 - Write CreatureTemplateModel
59/72 - Write CreatureTemplateQuestItem
60/72 - Write GameObjectTemplate
61/72 - Write GameObjectTemplateQuestItem
62/72 - Write ItemTemplate
63/72 - Write PlayerChoice
64/72 - Write PlayerChoiceResponse
65/72 - Write PlayerChoiceResponseReward
66/72 - Write PlayerChoiceResponseRewardCurrency
67/72 - Write PlayerChoiceResponseRewardFaction
68/72 - Write PlayerChoiceResponseRewardItem
69/72 - Write PageText
70/72 - Write NpcText
71/72 - Write ScenarioPOI
72/72 - Write ScenarioPOIPoint
[1/1 9.0.2.36839_2020-12-19_17-39-35.pkt]: Dumping sql: Saved file to '2021_01_03_19_47_23_9.0.2.36839_2020-12-19_17-39-35.pkt.sql'
Finished SQL file in 00:00:03.564.
```

**Comment by xXBentRealityXx** [comment]
@osleyder85 Sorry, I know this doesn't pertain to your issue, but could you contact me on Discord and let me know where to get a sniffer for retail? My username is Bent#1398
