### ISSUE TITLE
GameObjectTemplate: Unknown column 'RequiredLevel' in 'field list' - 8.2.0.31478

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#585]
TrinityCore - WowPacketParser
Detected build: V8_2_0_31478
Detected locale: enUS
Targeted database: BattleForAzeroth
Parsing date: 01/23/2021 23:55:26

```
60/72 - Error: Failed writing GameObjectTemplate
WowPacketParser Error: 0 : MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'RequiredLevel' in 'field list'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at WowPacketParser.SQL.SQLDatabase.Get[T](RowList`1 rowList, String database) in D:\WoW Tools\WowPacketParser\WowPacketParser\SQL\SQLDatabase.cs:line 241
   at WowPacketParser.SQL.SQLDatabase.Get[T](IEnumerable`1 conditionList, String database) in D:\WoW Tools\WowPacketParser\WowPacketParser\SQL\SQLDatabase.cs:line 233
   at WowPacketParser.SQL.Builders.WDBTemplates.GameObjectTemplate(Dictionary`2 gameobjects) in D:\WoW Tools\WowPacketParser\WowPacketParser\SQL\Builders\WDBTemplates.cs:line 158
```

**Comment by funjoker** [comment]
Running your WPP with Shadowlands database?

**Comment by funjoker** [comment]
Don't use Targeted database: BattleForAzeroth if DB is already Shadowlands.
