### ISSUE TITLE
Error: Failed writing ConversationActorTemplatesData

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#616]
TrinityCore - WowPacketParser
File name: Eversong Woods - Mage - 9.1.0.40120 Parte 3.pkt
Detected build: V9_1_0_40120
Detected locale: enUS
Targeted database: Shadowlands
Parsing date: 09/14/2021 21:53:09
```
5/72 - Error: Failed writing ConversationActorTemplatesData
WowPacketParser Error: 0 : MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'world.conversation_actor_template' doesn't exist
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at WowPacketParser.SQL.SQLDatabase.Get[T](RowList`1 rowList, String database) in I:\WoW Tools\WowPacketParser\WowPacketParser\SQL\SQLDatabase.cs:line 250
   at WowPacketParser.SQL.SQLDatabase.Get[T](IEnumerable`1 conditionList, String database) in I:\WoW Tools\WowPacketParser\WowPacketParser\SQL\SQLDatabase.cs:line 231
   at WowPacketParser.SQL.Builders.Conversations.ConversationActorTemplatesData() in I:\WoW Tools\WowPacketParser\WowPacketParser\SQL\Builders\Conversations.cs:line 36
```

**Comment by mdX7** [comment]
Thats a problem with ur db. The table `conversation_actor_template` does not exist in your `world` db. (Maybe ur world db is not called `world` in MySQL?)
You gotta use the same db name for world as you use it in the worldserver config for TrinityCore.

**Comment by Shauren** [comment]
But we dont have `conversation_actor_template`, its `conversation_actors`, might be a bug with c32bd8b3680cae65a9f6d2b740d44e7f21df96d2

**Comment by osleyder85** [comment]
Yes, it is really happening after this commit c32bd8b. I have the db well configured, what exists is the table 'world.conversation_actor_template' doesn't exist

**Comment by Shauren** [comment]
No, nevermind, this was always broken since they got changed in TC

**Comment by mdX7** [comment]
automatically disabled based on targeted database now ref 114defef4f7097034a20ee904dbc1ba692aff654
