### ISSUE TITLE
Parse reading db error 

### ISSUE THREAD

**Issue by Thordekk** [TrinityCore/WowPacketParser#636]
Loading DB...
Connecting to MySQL server: Server=localhost;Port=3306;Username=root;Database=wpp;CharSet=utf8;ConnectionTimeout=5;
System.IndexOutOfRangeException
Could not find specified column in results: SoundEntriesID1
   at MySql.Data.MySqlClient.ResultSet.GetOrdinal(String name)
   at MySql.Data.MySqlClient.MySqlDataReader.GetOrdinal(String name)
   at WowPacketParser.SQL.SQLDatabase.LoadBroadcastText() in C:\projects\wowpacketparser-191\WowPacketParser\SQL\SQLDatabase.cs:line 154
   at WowPacketParser.SQL.SQLDatabase.LoadSQL() in C:\projects\wowpacketparser-191\WowPacketParser\SQL\SQLDatabase.cs:line 80
   at WowPacketParser.SQL.SQLConnector.ReadDB() in C:\projects\wowpacketparser-191\WowPacketParser\SQL\SQLConnector.cs:line 111
Finished loading DB in 00:00:02.412.

Using last parser commit and last tc database up to date

**Comment by MaxtorCoder** [comment]
Sounds like an issue with you not running latest TC 😋

**Comment by Thordekk** [comment]
Ok thanks Max going to try again

**Comment by Shauren** [comment]
it IS bugged

**Comment by Rushor** [comment]
Is the newest nightly build including that fix?

**Comment by funjoker** [comment]
yes sir

**Comment by Rushor** [comment]
thank you!

**Comment by Rushor** [comment]
Parser works nicely now, people must make sure to enable the db and add master, hotfix and wpp database from https://github.com/TrinityCore/WowPacketParser/tree/master/SQL (wpp) and latest db world + hotfix from master branch + the updates in it: https://github.com/TrinityCore/TrinityCore/tree/master/sql/updates/world/master + https://github.com/TrinityCore/TrinityCore/tree/master/sql/updates/hotfixes/master
