### ISSUE TITLE
Is DBEnabled actually works on 9.1.5?

### ISSUE THREAD

**Issue by Stayer** [TrinityCore/WowPacketParser#644]
I tried to run WPP with this flag, but catch an exception:

"The given key '29779' was not present in the dictionary."

```
System.Collections.Generic.KeyNotFoundException
The given key '29779' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.MySqlField.set_CharacterSetIndex(Int32 value)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlCommand.ResetReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at WowPacketParser.SQL.SQLDatabase.LoadPointsOfinterest() in C:\WowPacketParser\SQL\SQLDatabase.cs:line 201
   at WowPacketParser.SQL.SQLDatabase.LoadSQL() in C:\WowPacketParser\WowPacketParser\SQL\SQLDatabase.cs:line 105
   at WowPacketParser.SQL.SQLConnector.ReadDB() in C:\WowPacketParser\WowPacketParser\SQL\SQLConnector.cs:line 111
Finished loading DB in 00:11:41.117.
```
Last SQL before crash: `"SELECT ID, PositionX, PositionY, Icon, Flags, Importance, Name FROM world.points_of_interest ORDER BY ID;"`

**TrinityCore rev. e00b1df36ec0 2021-12-25 22:46:46 +0100 (master branch) (Unix, RelWithDebInfo, Static)
TDB 915.21111**

**Comment by Shauren** [comment]
And whats your mysql version? Is it even mysql or mariadb?

**Comment by Stayer** [comment]
mariadb 10.3

**Comment by Shauren** [comment]
Then try it with mysql

**Comment by Stayer** [comment]
It works, thanks!
