### ISSUE TITLE
Crashes: Specified argument was out of the range of valid values - 9.1.0.38627

### ISSUE THREAD

**Issue by osleyder85** [TrinityCore/WowPacketParser#685]
```
[1/1 9.1.0.38627.pkt] System.ArgumentOutOfRangeException
[1/1 9.1.0.38627.pkt] Specified argument was out of the range of valid values.
[1/1 9.1.0.38627.pkt]    at WowPacketParser.Misc.ClientVersion.GetVersionDefiningBuild(ClientVersionBuild build) in I:\WoW Tools\WowPacketParser\WowPacketParser\Misc\ClientVersion.cs:line 958
   at WowPacketParser.Misc.ClientVersion.SetVersion(ClientVersionBuild version) in I:\WoW Tools\WowPacketParser\WowPacketParser\Misc\ClientVersion.cs:line 1056
   at WowPacketParser.Loading.BinaryPacketReader.SetBuild(UInt32 build) in I:\WoW Tools\WowPacketParser\WowPacketParser\Loading\BinaryPacketReader.cs:line 130
   at WowPacketParser.Loading.BinaryPacketReader.ReadHeader() in I:\WoW Tools\WowPacketParser\WowPacketParser\Loading\BinaryPacketReader.cs:line 93
   at WowPacketParser.Loading.BinaryPacketReader..ctor(SniffType type, String fileName, Encoding encoding) in I:\WoW Tools\WowPacketParser\WowPacketParser\Loading\BinaryPacketReader.cs:line 37
   at WowPacketParser.Loading.Reader.GetPacketReader(String fileName, SniffType type) in I:\WoW Tools\WowPacketParser\WowPacketParser\Loading\Reader.cs:line 28
   at WowPacketParser.Loading.SniffFile.ProcessFileImpl() in I:\WoW Tools\WowPacketParser\WowPacketParser\Loading\SniffFile.cs:line 193
   at WowPacketParser.Loading.SniffFile.ProcessFile() in I:\WoW Tools\WowPacketParser\WowPacketParser\Loading\SniffFile.cs:line 91
Processing 1 sniffs took 00:00:00.144.
```

**Comment by mdX7** [comment]
thats a ptr build, we are not supporting mainline ptr builds due to possibility of a lot of opcode changes
