### ISSUE TITLE
SMSG_GARRISON_COMPLETE_MISSION_RESULT not fully readed 

### ISSUE THREAD

**Issue by Thordekk** [TrinityCore/WowPacketParser#732]
[5] FollowerDBID: 0
System.IO.EndOfStreamException
Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at WowPacketParser.Misc.Packet.ReadUInt32(String name, Object[] indexes) in C:\Users\thord\Desktop\shadowlandsparser\WowPacketParser\Misc\PacketReads.cs:line 382
   at WowPacketParserModule.V7_0_3_22248.Parsers.GarrisonHandler.HandleGarrisonFinishMission(Packet packet) in C:\Users\thord\Desktop\shadowlandsparser\WowPacketParserModule.V7_0_3_22248\Parsers\GarrisonHandler.cs:line 331
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in C:\Users\thord\Desktop\shadowlandsparser\WowPacketParser\Parsing\Handler.cs:line 149

**Comment by funjoker** [comment]
which sniff version

**Comment by Thordekk** [comment]
9.2.7 last build
