### ISSUE TITLE
Error parse Woltk Classic sniff version

### ISSUE THREAD

**Issue by leelf00** [TrinityCore/WowPacketParser#733]
I got error when parse Woltk Classic sniff version.Full log below.

PS D:\ymir\WPP\Release> .\WowPacketParser.exe .\dump_3.4.0.46779_2022-11-26_22-28-25.pkt
Loading DB...
Connecting to MySQL server: Server=192.168.50.94;Port=3306;Username=root;Database=wpp;CharSet=utf8mb4;ConnectionTimeout=5;
SQL loaded in 00:00:51.489.
Finished loading DB in 00:02:28.732.

[1/1 dump_3.4.0.46779_2022-11-26_22-28-25.pkt] System.TypeInitializationException
[1/1 dump_3.4.0.46779_2022-11-26_22-28-25.pkt] The type initializer for 'WowPacketParser.Enums.Version.UpdateFields' threw an exception.
[1/1 dump_3.4.0.46779_2022-11-26_22-28-25.pkt]    at WowPacketParser.Enums.Version.UpdateFields.ResetUFDictionaries() in C:\projects\wowpacketparser-191\WowPacketParser\Enums\Version\UpdateFields.cs:line 29
   at WowPacketParser.Misc.ClientVersion.SetVersion(ClientVersionBuild version) in C:\projects\wowpacketparser-191\WowPacketParser\Misc\ClientVersion.cs:line 1132
   at WowPacketParser.Loading.BinaryPacketReader.SetBuild(UInt32 build) in C:\projects\wowpacketparser-191\WowPacketParser\Loading\BinaryPacketReader.cs:line 130
   at WowPacketParser.Loading.BinaryPacketReader.ReadHeader() in C:\projects\wowpacketparser-191\WowPacketParser\Loading\BinaryPacketReader.cs:line 93
   at WowPacketParser.Loading.BinaryPacketReader..ctor(SniffType type, String fileName, Encoding encoding) in C:\projects\wowpacketparser-191\WowPacketParser\Loading\BinaryPacketReader.cs:line 37
   at WowPacketParser.Loading.Reader.GetPacketReader(String fileName, SniffType type) in C:\projects\wowpacketparser-191\WowPacketParser\Loading\Reader.cs:line 28
   at WowPacketParser.Loading.SniffFile.ProcessFileImpl() in C:\projects\wowpacketparser-191\WowPacketParser\Loading\SniffFile.cs:line 193
   at WowPacketParser.Loading.SniffFile.ProcessFile() in C:\projects\wowpacketparser-191\WowPacketParser\Loading\SniffFile.cs:line 91
Processing 1 sniffs took 00:00:00.204.

**Comment by mdX7** [comment]
Update wpp to min https://github.com/TrinityCore/WowPacketParser/commit/131403256ba921765597afe705edcbadc059affb

**Comment by leelf00** [comment]
I download from nightly build link https://ci.appveyor.com/api/projects/DDuarte/wowpacketparser-191/artifacts/WowPacketParser/WPP.zip?job=Image:%20Visual%20Studio%202022;%20Configuration:%20Release&branch=master.
Is the nightly build lower than https://github.com/TrinityCore/WowPacketParser/commit/131403256ba921765597afe705edcbadc059affb

**Comment by funjoker** [comment]
appveyor is broken (the red x marks it)

**Comment by funjoker** [comment]
appveyor is broken atm.
We gonna drop appveyor soon and use github artifacts

**Comment by leelf00** [comment]
Thanks.I will build it myself.

**Comment by jackpoz** [comment]
Only Ubuntu build is broken on AppVeyor, Windows build works fine
