### ISSUE TITLE
Playerchoice errors

### ISSUE THREAD

**Issue by Thordekk** [TrinityCore/WowPacketParser#779]
**System.ArgumentException
Requested value '    ' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at WowPacketParser.Misc.ClientLocale.get_PacketLocale() in C:\Users\Luis\Desktop\shadowlandsparser\WowPacketParser\Misc\ClientLocale.cs:line 14
   at WowPacketParserModule.V9_0_1_36216.Parsers.QuestHandler.ReadPlayerChoiceResponse(Packet packet, Int32 choiceId, UInt32 index, Object[] indexes) in C:\Users\Luis\Desktop\shadowlandsparser\WowPacketParserModule.V9_0_1_36216\Parsers\QuestHandler.cs:line 670
   at WowPacketParserModule.V9_0_1_36216.Parsers.QuestHandler.HandleDisplayPlayerChoice(Packet packet) in C:\Users\Luis\Desktop\shadowlandsparser\WowPacketParserModule.V9_0_1_36216\Parsers\QuestHandler.cs:line 550
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in C:\Users\Luis\Desktop\shadowlandsparser\WowPacketParser\Parsing\Handler.cs:line 192
**
latest 10.1 client

**Comment by ateves** [comment]
Thordekk,

what happened?

**Comment by Thordekk** [comment]
Error parsing player choices try with 10.1 sniffs

**Comment by shamage** [comment]
I tried one older version of the release with this result: 
![Ashampoo_Snap_sobota 28  septembra 2024_22h1m40s](https://github.com/user-attachments/assets/d730636a-249e-4c50-aeba-e52a64a33dbf)
