### ISSUE TITLE
Exception on WowPacketParser.Enums.Version.UpdateFields when extracting Classic Era dump

### ISSUE THREAD

**Issue by ellingtonsantos** [TrinityCore/WowPacketParser#780]
After one of latest commits, I get this erros when parsing WoW Classic Era dump.

Commit: 7ba63ba
Client Build: 49821 and before

```
[1/1 dump_1.14.3.49821_2023-06-23_17-14-01.pkt] System.TypeInitializationException
[1/1 dump_1.14.3.49821_2023-06-23_17-14-01.pkt] The type initializer for 'WowPacketParser.Enums.Version.UpdateFields' threw an exception.
[1/1 dump_1.14.3.49821_2023-06-23_17-14-01.pkt]    at WowPacketParser.Enums.Version.UpdateFields.ResetUFDictionaries() in /src/WowPacketParser/Enums/Version/UpdateFields.cs:line 29
   at WowPacketParser.Misc.ClientVersion.SetVersion(ClientVersionBuild version) in /src/WowPacketParser/Misc/ClientVersion.cs:line 1232
   at WowPacketParser.Loading.BinaryPacketReader.SetBuild(UInt32 build) in /src/WowPacketParser/Loading/BinaryPacketReader.cs:line 131
   at WowPacketParser.Loading.BinaryPacketReader.ReadHeader() in /src/WowPacketParser/Loading/BinaryPacketReader.cs:line 94
   at WowPacketParser.Loading.BinaryPacketReader..ctor(SniffType type, String fileName, Encoding encoding) in /src/WowPacketParser/Loading/BinaryPacketReader.cs:line 38
   at WowPacketParser.Loading.Reader.GetPacketReader(String fileName, SniffType type) in /src/WowPacketParser/Loading/Reader.cs:line 28
   at WowPacketParser.Loading.Reader..ctor(String fileName, SniffType type) in /src/WowPacketParser/Loading/Reader.cs:line 18
   at WowPacketParser.Loading.SniffFile.ProcessFileImpl() in /src/WowPacketParser/Loading/SniffFile.cs:line 193
   at WowPacketParser.Loading.SniffFile.ProcessFile() in /src/WowPacketParser/Loading/SniffFile.cs:line 91
```

**Comment by ellingtonsantos** [comment]
Solved adding 1.14.3.49821
