### ISSUE TITLE
10.2.0.52808 SQL error

### ISSUE THREAD

**Issue by Flashaholic88** [TrinityCore/WowPacketParser#819]
whats wrong here?

[dump_10.2.0.52808_2024-01-11_20-54-00.zip](https://github.com/TrinityCore/WowPacketParser/files/13908295/dump_10.2.0.52808_2024-01-11_20-54-00.zip)
[WowPacketParser.dll.md](https://github.com/TrinityCore/WowPacketParser/files/13908296/WowPacketParser.dll.md)

```
C:\Users\Robert\Desktop\WPP-windows-latest-Release>WowPacketParser.exe dump_10.2.0.52808_2024-01-11_20-54-00.pkt
Loading module WowPacketParserModule.V9_0_1_36216.dll (fallback)
Loading module WowPacketParserModule.V8_0_1_27101.dll (fallback)
Loading module WowPacketParserModule.V7_0_3_22248.dll (fallback)
Loading module WowPacketParserModule.V6_0_2_19033.dll (fallback)
Loading module WowPacketParserModule.V10_0_0_46181.dll
[1/1 dump_10.2.0.52808_2024-01-11_20-54-00.pkt]: Parsing 4.6MB of packets. Detected version V10_2_0_52808
Processing... 100% complete
[1/1 dump_10.2.0.52808_2024-01-11_20-54-00.pkt]: Saved file to 'dump_10.2.0.52808_2024-01-11_20-54-00_parsed.txt'
[1/1 dump_10.2.0.52808_2024-01-11_20-54-00.pkt]: Parsed 10358 (93.865%) packets successfully, 118 (1.069%) with errors, skipped 3 (0.027%) and without structure 556 (5.039%)  (total: 11035) in 00:00:01.658
[1/1 dump_10.2.0.52808_2024-01-11_20-54-00.pkt] System.ArgumentOutOfRangeException
[1/1 dump_10.2.0.52808_2024-01-11_20-54-00.pkt] Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
[1/1 dump_10.2.0.52808_2024-01-11_20-54-00.pkt]    at System.Collections.Generic.List`1.get_Item(Int32 index)
   at WowPacketParser.Store.Objects.ConversationTemplate.LoadValuesFromUpdateFields() in D:\a\WowPacketParser\WowPacketParser\WowPacketParser\Store\Objects\ConversationTemplate.cs:line 84
   at WowPacketParser.SQL.Builder.DumpSQL(String prefix, String fileName, String header) in D:\a\WowPacketParser\WowPacketParser\WowPacketParser\SQL\Builder.cs:line 135
   at WowPacketParser.Loading.SniffFile.WriteSQLs() in D:\a\WowPacketParser\WowPacketParser\WowPacketParser\Loading\SniffFile.cs:line 570
   at WowPacketParser.Loading.SniffFile.ProcessFileImpl() in D:\a\WowPacketParser\WowPacketParser\WowPacketParser\Loading\SniffFile.cs:line 319
   at WowPacketParser.Loading.SniffFile.ProcessFile() in D:\a\WowPacketParser\WowPacketParser\WowPacketParser\Loading\SniffFile.cs:line 91
Processing 1 sniffs took 00:00:01.698.
```

**Comment by meji46** [comment]
Fixed by https://github.com/TrinityCore/WowPacketParser/commit/c61af375ad3e64e7ae153c7f261132585006cc56
