### ISSUE TITLE
`SMSG_UPDATE_OBJECT` does not seem to be entirely accurate for 3.4.2 50172 (50129)

### ISSUE THREAD

**Issue by heyitsbench** [TrinityCore/WowPacketParser#826]
Trying to parse a packet from 50172 and there are quite a few creature GUIDs that show up and are being used, but the initial `SMSG_UPDATE_OBJECT` responsible for their appearance doesn't seem to be parsing fully. No idea if this is the particular packet for the specific creature I'm having issues with, but this was the nearest UPDATE_OBJECT with an explicit exception:
```
ServerToClient: SMSG_UPDATE_OBJECT (0x27D1) Length: 1959 ConnIdx: 1 Time: [] Number: []
NumObjUpdates: 4
MapID: 1 (1)
HasRemovedObjects: False
Data size: 1948
[0] UpdateType: Values
[0] Object Guid: Full: 0x[] Player/0 R[]/S[] Map: 0 Low: []
System.ArgumentOutOfRangeException
Non-negative number required. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveRange(Int32 index, Int32 count)
   at WowPacketParser.Misc.DynamicUpdateField`1.Resize(UInt32 newSize) in C:\Users\benjy\Documents\GitHub\WowPacketParser\WowPacketParser\Misc\DynamicUpdateField.cs:line 25
   at WowPacketParser.Misc.DynamicUpdateField`1.ReadUpdateMask(Packet packet, Int32 bitSizeCount) in C:\Users\benjy\Documents\GitHub\WowPacketParser\WowPacketParser\Misc\DynamicUpdateField.cs:line 37
   at WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_2_50129.UpdateFieldHandler.ReadUpdatePlayerData(Packet packet, Object[] indexes) in C:\Users\benjy\Documents\GitHub\WowPacketParser\WowPacketParserModule.V3_4_0_45166\Parsers\UpdateFieldsHandler342.cs:line 1547
   at WowPacketParserModule.V2_5_1_38707.Parsers.UpdateHandler.HandleUpdateObject(Packet packet) in C:\Users\benjy\Documents\GitHub\WowPacketParser\WowPacketParserModule.V2_5_1_38707\Parsers\UpdateHandler.cs:line 103
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in C:\Users\benjy\Documents\GitHub\WowPacketParser\WowPacketParser\Parsing\Handler.cs:line 149
```

**Comment by heyitsbench** [comment]
I get errors and incorrect parsing from this opcode very often with 3.4.1/3.4.2. 😢

**Comment by sudlud** [comment]
I would also appreciate a fix
