### ISSUE TITLE
SMSG_GOSSIP_OPTION_NPC_INTERACTION Exception parsing

### ISSUE THREAD

**Issue by BrewingCoder** [TrinityCore/WowPacketParser#843]
Current retail, current code base as of this message.

```
ServerToClient: SMSG_GOSSIP_OPTION_NPC_INTERACTION (0x2AA7) Length: 17 ConnIdx: 1 Time: 03/29/2024 14:47:52.532 Number: 4406
GossipGUID: Full: 0x203CA400000137C0000006000002E3ED Creature/0 R3881/S6 Map: 0 Entry: 1247 Low: 189421
GossipNpcOptionID: 28213
System.NullReferenceException
Object reference not set to an instance of an object.
   at WowPacketParser.Parsing.Parsers.NpcHandler.AddGossipNpcOption(Int32 gossipNpcOptionId, TimeSpan timeSpan, Boolean checkDelay) in G:\wow_private\code\WowPacketParser\WowPacketParser\Parsing\Parsers\NpcHandler.cs:line 55
   at WowPacketParserModule.V10_0_0_46181.Parsers.NpcHandler.HandleGossipOptionNPCInteraction(Packet packet) in G:\wow_private\code\WowPacketParser\WowPacketParserModule.V10_0_0_46181\Parsers\NpcHandler.cs:line 22
   at WowPacketParser.Parsing.Handler.Parse(Packet packet, Boolean isMultiple) in G:\wow_private\code\WowPacketParser\WowPacketParser\Parsing\Handler.cs:line 146
```

**Comment by funjoker** [comment]
b97771439f9ea4892fa14f0b0a4353e7f6d8763e
